In [95]:
import numpy as np
import pandas as pd

In [96]:
df = pd.read_csv("customer.csv")

In [97]:
df.shape

(50, 5)

In [98]:
# separating ordinal and target columns
df = df.iloc[:, 2:]
df.sample(5)

review education purchased
23     Good    School        No
47     Good        PG       Yes
8   Average        UG        No
43     Poor        PG        No
36     Good        UG       Yes

In [99]:
df['review'].unique()

array(['Average', 'Poor', 'Good'], dtype=object)

In [100]:
df['education'].unique()

array(['School', 'UG', 'PG'], dtype=object)

In [101]:
from sklearn.model_selection import train_test_split

In [102]:
# splitting data into training and test sets before applying feature transformation i.e. ordinal encoding
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns="purchased"), df["purchased"], test_size=0.2)

In [103]:
X_train.head()

review education
36     Good        UG
30  Average        UG
35     Poor    School
27     Poor        PG
6      Good    School

In [104]:
X_test

review education
22     Poor        PG
1      Poor        UG
29  Average        UG
19     Poor        PG
0   Average    School
8   Average        UG
15     Poor        UG
16     Poor        UG
43     Poor        PG
28     Poor    School

In [105]:
from sklearn.preprocessing import OrdinalEncoder

In [106]:
oe = OrdinalEncoder(categories= [['Poor', 'Average',  'Good'], ['School', 'UG', 'PG']])
                        

In [107]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [108]:
X_train = oe.transform(X_train)
X_test = oe.transform(X_test)

In [110]:
X_test

array([[0., 2.],
       [0., 1.],
       [1., 1.],
       [0., 2.],
       [1., 0.],
       [1., 1.],
       [0., 1.],
       [0., 1.],
       [0., 2.],
       [0., 0.]])

In [111]:
X_train

array([[2., 1.],
       [1., 1.],
       [0., 0.],
       [0., 2.],
       [2., 0.],
       [1., 0.],
       [2., 0.],
       [0., 2.],
       [1., 0.],
       [0., 2.],
       [1., 1.],
       [1., 2.],
       [1., 2.],
       [2., 0.],
       [2., 2.],
       [0., 2.],
       [0., 2.],
       [2., 2.],
       [0., 2.],
       [2., 1.],
       [1., 0.],
       [2., 0.],
       [2., 1.],
       [2., 1.],
       [1., 0.],
       [0., 1.],
       [2., 0.],
       [2., 2.],
       [1., 1.],
       [2., 2.],
       [0., 0.],
       [2., 1.],
       [2., 1.],
       [0., 0.],
       [2., 2.],
       [0., 0.],
       [2., 2.],
       [1., 1.],
       [2., 0.],
       [1., 2.]])

In [112]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [113]:
# LabelEncoder for target column
from sklearn.preprocessing import LabelEncoder


In [118]:
y_train.head()

36    Yes
30     No
35    Yes
27     No
6      No
Name: purchased, dtype: object

In [119]:
y_test.head()

22    Yes
1      No
29    Yes
19    Yes
0      No
Name: purchased, dtype: object

In [120]:
le = LabelEncoder()

In [121]:
le.fit(y_train)

LabelEncoder()

In [122]:
y_train = le.transform(y_train)

In [123]:
y_test = le.transform(y_test)

In [124]:
y_train

array([1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0])

In [125]:
y_test

array([1, 0, 1, 1, 0, 0, 0, 1, 0, 0])